#!/usr/bin/python2.3

# -*- coding: ISO-8859-1 -*-
# Copyright 2003, 2004 Fundación Vía Libre
#
# This file is part of Xot.
#
# Xot is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Xot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Xot; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import user, sys;

try:
    import xot.exotic;
except ImportError:
    print """
Tenés que editar ~/.pythonrc.py para que le agregue a sys.path el directorio
donde se encuentra exotic.py. Algo como lo siguiente:

    import sys, os
    sys.path.append(os.environ['HOME'] + "/src/cvs/papo/xot/")
    del sys
    del os
"""
    sys.exit()
xot.exotic.main();
